### ISSUE TITLE
CFP form spanish proposal unclear error

### ISSUE THREAD

**Issue by AlexOteiza-Personal** [EuroPython/epcon#116] opened 2015-03-19 14:57 UTC
The form submit fails if the proposal fields are set like in the following image:
After submitting, the language option highlights with red, but no error message is displayed.

![image](https://cloud.githubusercontent.com/assets/1060784/6733011/a789e576-ce4f-11e4-8a71-75375cf45faf.png)

**Comment by malemburg** [comment] 2015-03-19 16:36
I can reproduce this on the production system. The form reports "Value u'es' is not a valid choice.".

However, I don't get the error on my development instance.

**Comment by malemburg** [comment] 2015-03-19 16:40
@AlexOteiza: For now, please file the talk as "English" and then change it back to "Spanish" once this issue is resolved. Thanks.

**Comment by malemburg** [comment] 2015-03-19 16:41
This looks like a bug in the conference app. I made some local changes to it that I need to get into the site somehow... also see #114.

**Comment by aramboi** [comment] 2019-07-21 20:12
Fixed in as part of #206 it seems.

**Closed as completed by aramboi** 2019-07-21 20:12 UTC
